/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    Cemetery: {
      address: "0xed791AC909e6530C097983626Ad8afa19B9EBe09",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "deceasedName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "plotId",
              type: "uint256",
            },
          ],
          name: "BurialCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "deceasedName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "plotId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "burialDate",
              type: "uint256",
            },
          ],
          name: "BurialScheduled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "plotId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "location",
              type: "string",
            },
          ],
          name: "PlotPurchased",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          name: "burialRecords",
          outputs: [
            {
              internalType: "uint256",
              name: "plotId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "deceasedName",
              type: "string",
            },
            {
              internalType: "address",
              name: "familyContact",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "burialDate",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "ceremony",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "familyPlots",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "funeralServiceContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_plotId",
              type: "uint256",
            },
          ],
          name: "getPlot",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "enum Cemetery.PlotType",
                  name: "plotType",
                  type: "uint8",
                },
                {
                  internalType: "enum Cemetery.PlotStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "price",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "location",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "occupantName",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "burialDate",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "epitaph",
                  type: "string",
                },
              ],
              internalType: "struct Cemetery.Plot",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "plots",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "enum Cemetery.PlotType",
              name: "plotType",
              type: "uint8",
            },
            {
              internalType: "enum Cemetery.PlotStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "location",
              type: "string",
            },
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "string",
              name: "occupantName",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "burialDate",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "epitaph",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_deceasedName",
              type: "string",
            },
            {
              internalType: "address",
              name: "_familyContact",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_burialDate",
              type: "uint256",
            },
          ],
          name: "prepareBurial",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_plotId",
              type: "uint256",
            },
          ],
          name: "purchasePlot",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_plotId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_epitaph",
              type: "string",
            },
          ],
          name: "setEpitaph",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_funeralService",
              type: "address",
            },
          ],
          name: "setFuneralServiceContract",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    FuneralService: {
      address: "0x19A5b5d35aDffA6EE4A706EFE12F6F3ed95d97c2",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "orderId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "deceasedName",
              type: "string",
            },
          ],
          name: "FuneralInitiated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "orderId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PaymentReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "orderId",
              type: "uint256",
            },
          ],
          name: "ServiceCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "orderId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum FuneralService.ServiceType",
              name: "serviceType",
              type: "uint8",
            },
          ],
          name: "ServiceConfirmed",
          type: "event",
        },
        {
          inputs: [],
          name: "cemeteryContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_orderId",
              type: "uint256",
            },
          ],
          name: "completeService",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_orderId",
              type: "uint256",
            },
            {
              internalType: "enum FuneralService.ServiceType",
              name: "_serviceType",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "_serviceDate",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_specialRequests",
              type: "string",
            },
          ],
          name: "confirmService",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "funeralOrders",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "deceasedName",
              type: "string",
            },
            {
              internalType: "address",
              name: "familyContact",
              type: "address",
            },
            {
              internalType: "enum FuneralService.ServiceType",
              name: "serviceType",
              type: "uint8",
            },
            {
              internalType: "enum FuneralService.ServiceStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "totalCost",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "initiatedTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "serviceDate",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "specialRequests",
              type: "string",
            },
            {
              internalType: "bool",
              name: "isPaid",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_orderId",
              type: "uint256",
            },
          ],
          name: "getFuneralOrder",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "patientId",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "deceasedName",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "familyContact",
                  type: "address",
                },
                {
                  internalType: "enum FuneralService.ServiceType",
                  name: "serviceType",
                  type: "uint8",
                },
                {
                  internalType: "enum FuneralService.ServiceStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "totalCost",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "initiatedTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "serviceDate",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "specialRequests",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "isPaid",
                  type: "bool",
                },
              ],
              internalType: "struct FuneralService.FuneralOrder",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "hospitalContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_patientId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_deceasedName",
              type: "string",
            },
            {
              internalType: "address",
              name: "_familyContact",
              type: "address",
            },
          ],
          name: "initiateFuneralProcess",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum FuneralService.ServiceType",
              name: "",
              type: "uint8",
            },
          ],
          name: "servicePrices",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_hospital",
              type: "address",
            },
            {
              internalType: "address",
              name: "_cemetery",
              type: "address",
            },
          ],
          name: "setExternalContracts",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_orderId",
              type: "uint256",
            },
          ],
          name: "startService",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum FuneralService.ServiceType",
              name: "_type",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "_price",
              type: "uint256",
            },
          ],
          name: "updateServicePrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    HospitalCore: {
      address: "0x133BaF2d5F59286906c7bA4E357158AF663792Ac",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "funeralContract",
              type: "address",
            },
          ],
          name: "FuneralServiceTriggered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "address",
              name: "familyContact",
              type: "address",
            },
          ],
          name: "PatientAdmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "PatientDeceased",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum HospitalCore.PatientStatus",
              name: "newStatus",
              type: "uint8",
            },
          ],
          name: "PatientStatusUpdated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "staff",
              type: "address",
            },
          ],
          name: "addMedicalStaff",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_age",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_familyContact",
              type: "address",
            },
            {
              internalType: "string",
              name: "_initialRecord",
              type: "string",
            },
          ],
          name: "admitPatient",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "cemeteryContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "familyPatients",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "funeralServiceContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_family",
              type: "address",
            },
          ],
          name: "getFamilyPatients",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_patientId",
              type: "uint256",
            },
          ],
          name: "getPatient",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "age",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "familyContact",
                  type: "address",
                },
                {
                  internalType: "enum HospitalCore.PatientStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "admissionTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lastUpdateTime",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "medicalRecord",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "hasFuneralPlan",
                  type: "bool",
                },
              ],
              internalType: "struct HospitalCore.Patient",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalPatients",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "medicalStaff",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nursingHomeContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "patients",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "age",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "familyContact",
              type: "address",
            },
            {
              internalType: "enum HospitalCore.PatientStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "admissionTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastUpdateTime",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "medicalRecord",
              type: "string",
            },
            {
              internalType: "bool",
              name: "hasFuneralPlan",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_patientId",
              type: "uint256",
            },
          ],
          name: "payForTreatment",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_nursingHome",
              type: "address",
            },
            {
              internalType: "address",
              name: "_funeralService",
              type: "address",
            },
            {
              internalType: "address",
              name: "_cemetery",
              type: "address",
            },
          ],
          name: "setExternalContracts",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_patientId",
              type: "uint256",
            },
            {
              internalType: "enum HospitalCore.PatientStatus",
              name: "_newStatus",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "_updateRecord",
              type: "string",
            },
          ],
          name: "updatePatientStatus",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    NursingHome: {
      address: "0x0A206B77d94498fEdCAaF23e4Dde0D1928153d96",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "residentId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ResidentAdmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "residentId",
              type: "uint256",
            },
          ],
          name: "ResidentDeceased",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "residentId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "hospital",
              type: "address",
            },
          ],
          name: "ResidentTransferred",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_age",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_familyContact",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_monthlyFee",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_healthCondition",
              type: "string",
            },
          ],
          name: "admitResident",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "familyResidents",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_residentId",
              type: "uint256",
            },
          ],
          name: "getResident",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "age",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "familyContact",
                  type: "address",
                },
                {
                  internalType: "enum NursingHome.ResidentStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "admissionDate",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "monthlyFee",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "healthCondition",
                  type: "string",
                },
              ],
              internalType: "struct NursingHome.Resident",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "hospitalContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "residents",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "age",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "familyContact",
              type: "address",
            },
            {
              internalType: "enum NursingHome.ResidentStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "admissionDate",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "monthlyFee",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "healthCondition",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_hospital",
              type: "address",
            },
          ],
          name: "setHospitalContract",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_residentId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_reason",
              type: "string",
            },
          ],
          name: "transferToHospital",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    YourContract: {
      address: "0x9E83669fdDAB559b13142ff036b525124F276eEE",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
  31337: {
    Cemetery: {
      address: "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "deceasedName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "plotId",
              type: "uint256",
            },
          ],
          name: "BurialCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "deceasedName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "plotId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "burialDate",
              type: "uint256",
            },
          ],
          name: "BurialScheduled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "plotId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "location",
              type: "string",
            },
          ],
          name: "PlotPurchased",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          name: "burialRecords",
          outputs: [
            {
              internalType: "uint256",
              name: "plotId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "deceasedName",
              type: "string",
            },
            {
              internalType: "address",
              name: "familyContact",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "burialDate",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "ceremony",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "familyPlots",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "funeralServiceContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_plotId",
              type: "uint256",
            },
          ],
          name: "getPlot",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "enum Cemetery.PlotType",
                  name: "plotType",
                  type: "uint8",
                },
                {
                  internalType: "enum Cemetery.PlotStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "price",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "location",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "occupantName",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "burialDate",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "epitaph",
                  type: "string",
                },
              ],
              internalType: "struct Cemetery.Plot",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "plots",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "enum Cemetery.PlotType",
              name: "plotType",
              type: "uint8",
            },
            {
              internalType: "enum Cemetery.PlotStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "location",
              type: "string",
            },
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "string",
              name: "occupantName",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "burialDate",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "epitaph",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_deceasedName",
              type: "string",
            },
            {
              internalType: "address",
              name: "_familyContact",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_burialDate",
              type: "uint256",
            },
          ],
          name: "prepareBurial",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_plotId",
              type: "uint256",
            },
          ],
          name: "purchasePlot",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_plotId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_epitaph",
              type: "string",
            },
          ],
          name: "setEpitaph",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_funeralService",
              type: "address",
            },
          ],
          name: "setFuneralServiceContract",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    FuneralService: {
      address: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "orderId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "deceasedName",
              type: "string",
            },
          ],
          name: "FuneralInitiated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "orderId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PaymentReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "orderId",
              type: "uint256",
            },
          ],
          name: "ServiceCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "orderId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum FuneralService.ServiceType",
              name: "serviceType",
              type: "uint8",
            },
          ],
          name: "ServiceConfirmed",
          type: "event",
        },
        {
          inputs: [],
          name: "cemeteryContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_orderId",
              type: "uint256",
            },
          ],
          name: "completeService",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_orderId",
              type: "uint256",
            },
            {
              internalType: "enum FuneralService.ServiceType",
              name: "_serviceType",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "_serviceDate",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_specialRequests",
              type: "string",
            },
          ],
          name: "confirmService",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "funeralOrders",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "deceasedName",
              type: "string",
            },
            {
              internalType: "address",
              name: "familyContact",
              type: "address",
            },
            {
              internalType: "enum FuneralService.ServiceType",
              name: "serviceType",
              type: "uint8",
            },
            {
              internalType: "enum FuneralService.ServiceStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "totalCost",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "initiatedTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "serviceDate",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "specialRequests",
              type: "string",
            },
            {
              internalType: "bool",
              name: "isPaid",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_orderId",
              type: "uint256",
            },
          ],
          name: "getFuneralOrder",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "patientId",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "deceasedName",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "familyContact",
                  type: "address",
                },
                {
                  internalType: "enum FuneralService.ServiceType",
                  name: "serviceType",
                  type: "uint8",
                },
                {
                  internalType: "enum FuneralService.ServiceStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "totalCost",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "initiatedTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "serviceDate",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "specialRequests",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "isPaid",
                  type: "bool",
                },
              ],
              internalType: "struct FuneralService.FuneralOrder",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "hospitalContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_patientId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_deceasedName",
              type: "string",
            },
            {
              internalType: "address",
              name: "_familyContact",
              type: "address",
            },
          ],
          name: "initiateFuneralProcess",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum FuneralService.ServiceType",
              name: "",
              type: "uint8",
            },
          ],
          name: "servicePrices",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_hospital",
              type: "address",
            },
            {
              internalType: "address",
              name: "_cemetery",
              type: "address",
            },
          ],
          name: "setExternalContracts",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_orderId",
              type: "uint256",
            },
          ],
          name: "startService",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum FuneralService.ServiceType",
              name: "_type",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "_price",
              type: "uint256",
            },
          ],
          name: "updateServicePrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    HospitalCore: {
      address: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "funeralContract",
              type: "address",
            },
          ],
          name: "FuneralServiceTriggered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "address",
              name: "familyContact",
              type: "address",
            },
          ],
          name: "PatientAdmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "PatientDeceased",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "patientId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum HospitalCore.PatientStatus",
              name: "newStatus",
              type: "uint8",
            },
          ],
          name: "PatientStatusUpdated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "staff",
              type: "address",
            },
          ],
          name: "addMedicalStaff",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_age",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_familyContact",
              type: "address",
            },
            {
              internalType: "string",
              name: "_initialRecord",
              type: "string",
            },
          ],
          name: "admitPatient",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "cemeteryContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "familyPatients",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "funeralServiceContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_family",
              type: "address",
            },
          ],
          name: "getFamilyPatients",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_patientId",
              type: "uint256",
            },
          ],
          name: "getPatient",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "age",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "familyContact",
                  type: "address",
                },
                {
                  internalType: "enum HospitalCore.PatientStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "admissionTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lastUpdateTime",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "medicalRecord",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "hasFuneralPlan",
                  type: "bool",
                },
              ],
              internalType: "struct HospitalCore.Patient",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalPatients",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "medicalStaff",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nursingHomeContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "patients",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "age",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "familyContact",
              type: "address",
            },
            {
              internalType: "enum HospitalCore.PatientStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "admissionTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastUpdateTime",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "medicalRecord",
              type: "string",
            },
            {
              internalType: "bool",
              name: "hasFuneralPlan",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_patientId",
              type: "uint256",
            },
          ],
          name: "payForTreatment",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_nursingHome",
              type: "address",
            },
            {
              internalType: "address",
              name: "_funeralService",
              type: "address",
            },
            {
              internalType: "address",
              name: "_cemetery",
              type: "address",
            },
          ],
          name: "setExternalContracts",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_patientId",
              type: "uint256",
            },
            {
              internalType: "enum HospitalCore.PatientStatus",
              name: "_newStatus",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "_updateRecord",
              type: "string",
            },
          ],
          name: "updatePatientStatus",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    NursingHome: {
      address: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "residentId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ResidentAdmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "residentId",
              type: "uint256",
            },
          ],
          name: "ResidentDeceased",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "residentId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "hospital",
              type: "address",
            },
          ],
          name: "ResidentTransferred",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_age",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_familyContact",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_monthlyFee",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_healthCondition",
              type: "string",
            },
          ],
          name: "admitResident",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "familyResidents",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_residentId",
              type: "uint256",
            },
          ],
          name: "getResident",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "age",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "familyContact",
                  type: "address",
                },
                {
                  internalType: "enum NursingHome.ResidentStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "admissionDate",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "monthlyFee",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "healthCondition",
                  type: "string",
                },
              ],
              internalType: "struct NursingHome.Resident",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "hospitalContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "residents",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "age",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "familyContact",
              type: "address",
            },
            {
              internalType: "enum NursingHome.ResidentStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "admissionDate",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "monthlyFee",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "healthCondition",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_hospital",
              type: "address",
            },
          ],
          name: "setHospitalContract",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_residentId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_reason",
              type: "string",
            },
          ],
          name: "transferToHospital",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    YourContract: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
